<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-KTPP931" ignored="0" name="RetryMultilpeFailedTestCases" tests="9" failures="2" timestamp="2021-10-09T18:32:34 IST" time="0.281" errors="0">
  <testcase name="test1" time="0.037" classname="mytests.myTests">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.004" classname="mytests.myTests">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.004" classname="mytests.myTests">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.003" classname="mytests.myTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.myTests.test1(myTests.java:10)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.003" classname="mytests.myTests">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.005" classname="mytests.myTests">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="mytests.myTests">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.004" classname="mytests.myTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.myTests.test2(myTests.java:15)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.003" classname="mytests.myTests"/>
</testsuite> <!-- RetryMultilpeFailedTestCases -->
